# LilyGO T-CAN485
# https://github.com/syssi/esphome-pace-bms/issues/54

substitutions:
  name: pace-bms
  friendly_name: "Pace BMS"
  device_description: "Monitor and control a PACE BMS via RS485 (Modbus)"
  tx_pin: GPIO22  # LilyGo-specific TX pin
  rx_pin: GPIO21  # LilyGo-specific RX pin

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-pace-bms"
    version: 2.1.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you're using Home Assistant, prefer API over MQTT
api:

output:
  # Enable the RS485 converter
  - platform: gpio
    id: ENABLE_PIN
    pin:
      number: GPIO19
      inverted: true

  # Enable autodirection
  - platform: gpio
    id: SE_PIN
    pin:
      number: GPIO17
      inverted: true

  # Enable 5V pin of the RS485 converter
  - platform: gpio
    id: ENABLE_5V_PIN
    pin:
      number: GPIO16
      inverted: true

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}  # LilyGo TX Pin
    rx_pin: ${rx_pin}  # LilyGo RX Pin
    debug:
      direction: BOTH
      dummy_receiver: false

modbus:
  - id: modbus0
    uart_id: uart_0
    send_wait_time: 200ms

modbus_controller:
  - id: bms0
    address: "0x01"
    modbus_id: modbus0
    command_throttle: 200ms
    update_interval: 10s

  - id: bms1
    address: "0x02"
    modbus_id: modbus0
    command_throttle: 200ms
    update_interval: 10s

  # - id: bms2
  #   address: "0x03"
  #   modbus_id: modbus0
  #   command_throttle: 200ms
  #   update_interval: 10s

  # - id: bms3
  #   address: "0x04"
  #   modbus_id: modbus0
  #   command_throttle: 200ms
  #   update_interval: 10s

# Include packages for each battery pack
packages:
  pack_1: !include
    file: pack.yaml
    vars:
      modbus_controller_id: bms0
      pack: Pack 1
      friendly_name: Pace BMS
  pack_2: !include
    file: pack.yaml
    vars:
      modbus_controller_id: bms1
      pack: Pack 2
      friendly_name: Pace BMS
#  pack_3: !include
#    file: pack.yaml
#    vars:
#      modbus_controller_id: bms2
#      pack: Pack 3
#      friendly_name: Pace BMS
#  pack_4: !include
#    file: pack.yaml
#    vars:
#      modbus_controller_id: bms3
#      pack: Pack 4
#      friendly_name: Pace BMS
